apiVersion: v1
entries:
  generate-secret:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-08-06T11:28:05.376259469+02:00"
    description: A Helm chart for Kubernetes
    digest: 1387d9d9ed2510deb6cedfc2bb64a8a4baa9af46bd851ad70d5fae598a3454fb
    name: generate-secret
    type: application
    urls:
    - generate-secret-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-08-06T11:28:05.373209893+02:00"
    description: A Helm chart for Kubernetes
    digest: fd915e6c4bc3d9c0b15b2e9c9004027512c6c052ed34222d771378465eb5d461
    name: generate-secret
    type: application
    urls:
    - generate-secret-0.1.0.tgz
    version: 0.1.0
generated: "2021-08-06T11:28:05.371959778+02:00"
