{{- if and (.Values.generateCredential) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "generate-secret.fullname" . }}
type: Opaque
stringData:
  access_key_id: {{ .Values.accessKeyId }}
  cloud: |
    [default]
    aws_access_key_id = {{ .Values.user.accessKeyId }}
    aws_secret_access_key = {{ template "generate-secret-access-key"  . }}
{{- end }}
