kind: Secret
apiVersion: v1
metadata:
  name: {{- include generate-secret.fullname }}
  annotations:
    avp.kubernetes.io/kv-version: "2"
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = {{- include "generate-access-key-id" }}
    aws_secret_access_key = {{- include "generate-secret-access-key" }}

