kind: Secret
apiVersion: v1
metadata:
  name: {{ template "generate-secret.fullname" . }}
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = {{ template "generate-access-key-id" . }}
    aws_secret_access_key = {{ template "generate-secret-access-key"  . }}

